name: Deploy new code to server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Fix git safe directory
        run: git config --global --add safe.directory /home/ubuntu/Flask-portfolio    
      - name: update the user to root user
        run: |
          sudo su
      - name: pull latest changes to server
        working-directory: /home/ubuntu/Flask-portfolio
        run: |
          git fetch origin
          git reset --hard origin/main
      - name: restart the server
        run: |
            echo "Restarting the server..."
            sudo systemctl restart portfolio
      - name: check the status of the service
        run: |
            echo "Checking the status of the service..."
            sudo systemctl status portfolio

